version: "3"
services:
  laravel:
    image: jeysonlesmes/lumen-supervisor:8
    container_name: test_app
    volumes:
      - .:/workspace
    ports:
      - "91:80"
    networks:
      - app
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3332:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_DATABASE: 'test_app'
    networks:
      - app
networks:
  app:
    driver: bridge